### ISSUE TITLE
Extrair sprites pelo serverId

### ISSUE THREAD

**Issue by icarodantas123** [ottools/ItemEditor#11]
Cara tem uma coisa que eu queria te pedir... Nossa mano ia ficar muuuuuito show!!! :D
Tipo, ter uma opção de extrair as sprites dos items em .gif! Eu sei que o Object Builder já faz isso, mas eu queria que ele extraísse tudo pelo serverid não pelo clientid e além do mais, as sprites que fossem animadas ele extraia em .gif com a respectiva velocidade entre os frames :D!!! Não precisaria extrair as otfits, por que tem as camadas lá, etc...
:D

**Comment by Mignari** [comment]
Não é o objetivo do programa.
