### ISSUE TITLE
Inconsistent scrolling

### ISSUE THREAD

**Issue by Erza** [ottools/ItemEditor#13]
When scrolling through the item list, it doesn't scroll by a consistent distance, it scrolls further upwards than it does downwards, this makes navigation really awkward.

The issue started happening after this commit: https://github.com/ottools/ItemEditor/commit/091a663673ef6dca237e36722ba7a05ac19d364b

In [this video](https://streamable.com/ukvyzc) you can see a demonstration of the issue, all I'm doing is scrolling up and down in an alternating pattern, and eventually I end up at the beginning of the list again.

**Comment by Mignari** [comment]
Thanks
