### ISSUE TITLE
Cannot load otb

### ISSUE THREAD

**Issue by ricardoianelli** [ottools/ItemEditor#16]
Here's an image of the error.
I've tried to compile as "8.60v1" too, but the error persists.
![error](https://cloud.githubusercontent.com/assets/2482654/20690788/c21df2ea-b5b3-11e6-9142-be7b8f0d6af4.png)

**Comment by Mignari** [comment]
Your otb version is 19 and the client signatures are for otb version 20. Replace both lines with
``` xml
<client version="860" description="Client 8.60" otbversion="19" datsignature="4C2C7993" sprsignature="4C220594"/>
```

**Comment by ricardoianelli** [comment]
Thanks! Also had other error, but it was caused because the client was inside Dropbox folder. Already solved! Thanks!
