### ISSUE TITLE
Items.otb 10.56

### ISSUE THREAD

**Issue by Ravene** [ottools/ItemEditor#2]
hey, its supported items.otb 10.56? because i don't see it on,but i need it.

<client version="1056" description="Client 10.56" otbversion="55" datsignature="5383504E" sprsignature="53835077"/>

what is otbversion? objectbuilder have it as 0 in tibia 10.41 but there is 55

**Comment by Mignari** [comment]
Yes, this version is supported.
The otbversion is 56, so you need to **replace** the version 10.77 in PluginThree.xml

**Comment by Ravene** [comment]
solved,thanks but i see RME doesn't have support 10.56 just 10.57
