### ISSUE TITLE
Ladder bug

### ISSUE THREAD

**Issue by beastn** [ottools/ItemEditor#9]
If we edit out items.otb with this (10.76) we cannot use the cormaya ladder (In ORTS Datapack) and if there is an item on the bottom of the ladder we cannot use the ladder.

**Comment by paulosalvatore** [comment]
Bump? Got the same here

**Comment by paulosalvatore** [comment]
Actual OtItemEditor is not reading forceUse Flag. There is a need of a update in OtItemEditor.

**Comment by Mignari** [comment]
can you check if it was fixed?
https://github.com/ottools/ItemEditor/releases/tag/v0.3.6

**Comment by paulosalvatore** [comment]
Fixed for me! Thanks

**Comment by Mignari** [comment]
Fixed this in 9438fad
